[package]
name = "egui_extras_xt"
version = "0.1.0"
authors = ["Nagy Tibor <xnagytibor@protonmail.com>"]
license = "MIT"
edition = "2021"

[badges]
maintenance = { status = "as-is" }

[dependencies]
egui = "0.19.0"
emath = "0.19.0"
epaint = "0.19.0"
itertools = "0.10.3"

barcoders = { version = "1.0.2", optional = true }
qrcode = { version = "0.11.2", optional = true, default-features = false }

[features]
barcodes = ["dep:barcoders", "dep:qrcode"]
compasses = []
displays = []
knobs = []
