[package]
name = "egui_extras_xt_example"
version = "0.1.0"
authors = ["Nagy Tibor <xnagytibor@protonmail.com>"]
license = "MIT"
edition = "2021"

[badges]
maintenance = { status = "as-is" }

[dependencies]
egui_extras_xt = { path = "../egui_extras_xt/" }

eframe = "0.18.0"
itertools = "0.10.3"
